### ISSUE TITLE
PATH entries with spaces don't get parsed correctly

### ISSUE THREAD

**Issue by strayer** [diasjorge/emacs-load-env-vars#4]
I have a path with a space in it in my PATH env. load-env-vars seems to have issues with this when loading the environment variable.

This is how my PATH looks:
`PATH=/Users/work/.bin:/usr/local/sbin:/Users/work/Library/Android/sdk/tools:/Users/work/Library/Android/sdk/platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin:/Applications/Wireshark.app/Contents/MacOS:/Users/work/Library/Python/3.7/bin:/Users/work/.asdf/shims:/Users/work/.asdf/bin`

It seems like values following the space are ignored, since exec-path ends up like this:
exec-path: `("/Users/work/.bin" "/usr/local/sbin" "/Users/work/Library/Android/sdk/tools" "/Users/work/Library/Android/sdk/platform-tools" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/opt/X11/bin" "/Applications/VMware" "/usr/local/Cellar/emacs-plus/26.2/libexec/emacs/26.2/x86_64-apple-darwin18.2.0/")`

See https://github.com/hlissner/doom-emacs/issues/1322#issuecomment-490822565 for reference.

**Comment by diasjorge** [comment]
Hi @Strayer, the problem is that a whitespace is not valid without quotes. In bash you'd need to quote such a value.
```
KEY="value with space"
```

**Comment by strayer** [comment]
Hey @diasjorge, you are right of course. Sorry for the hassle!
